.Dd August 10, 2014
.Dt MKMNFST 1
.Os
.Sh NAME
.Nm mkmnfst
.Nd post your PGP-signed manifesto to mnfst
.Sh SYNOPSIS
.Nm mkmnfst
.Op Fl 0
.Op Fl s Ar server_name
.Op file
.Sh DESCRIPTION
The
.Nm
utility posts a manifesto to mnfst.
This manifesto is signed with your PGP key.
.
If a file is passed, that file is posted.
If no file is passed it opens your editor, then posts the resulting file.
Abnormally terminating your editor cancels the program.
It supports these options and arguments:
.
.Bl -tag
.It Fl 0
Use HTTP instead of HTTPS to connect to the server.
This is typically less secure and not supported by most servers so only disable
HTTPS if you know what you are doing.
This flag is a zero, not the vowel.
.It Fl s Ar server_name
Send the manifesto to
.Ar server_name
instead of the default server.
.El
.Sh ENVIRONMENT
.Bl -tag -width PKG_TMPDIR
.It Ev VISUAL
The editor to use when the user passes no file.
If
.Ev VISUAL
is not set, fall back to
.Ev EDITOR .
If
.Ev EDITOR
is not set, fall back to
.Pa /bin/ed .
The value of
.Ev VISUAL
must be the path to an editor that runs in the foreground.
.El
.\" .Sh FILES
.\" .Sh EXIT STATUS
.\" For sections 1, 6, and 8 only.
.\" .Sh EXAMPLES
.\" .Sh DIAGNOSTICS
.\" For sections 1, 4, 6, 7, 8, and 9 printf/stderr messages only.
.\" .Sh ERRORS
.\" For sections 2, 3, 4, and 9 errno settings only.
.Sh SEE ALSO
.Lk https://mnfst.io/ mnfst
.\" .Sh STANDARDS
.\" .Sh HISTORY
.Sh AUTHORS
.An -split
.An "Mike Burns" Aq Mt mike@mike-burns.com
.\" .Sh CAVEATS
.\" .Sh BUGS
